### ISSUE TITLE
How can I use filters to call for all transactions that were made since a specific day

### ISSUE THREAD

**Issue by supre** [springboardretail/springboard-docs#2]
Currently I am trying to use something like this:
https://{{subdomain}}.myspringboard.us/api/inventory/transactions?page=1&per_page=100&~[created_at][$gt]=2013-04-19

Is this the way it's supposed to be done or am I making some mistake in my query?

**Comment by jstotz** [comment]
That looks correct to me and appeared to return the correct results in my test. Is it returning the results you expected?

**Comment by supre** [comment]
Aaha my bad, it was working fine. BTW, I didn't find any example on how to sort. How can I sort my returned rows based on `created_at`?

**Comment by jstotz** [comment]
Sure, I'll get the docs updated to cover sorting. In the meantime, here are some examples:

Ascending (default):

https://{{subdomain}}.myspringboard.us/api/inventory/transactions?page=1&per_page=100&~[created_at][$gt]=2013-04-19**&sort[]=created_at**

Descending:

https://{{subdomain}}.myspringboard.us/api/inventory/transactions?page=1&per_page=100&~[created_at][$gt]=2013-04-19**&sort[]=created_at,desc**

If you need to sort by multiple properties you can specify the `sort[]` parameter multiple times. Sorts will be applied in the order in which they're given.

**Comment by supre** [comment]
Aaha that works, thanks
